import { headers } from 'next/headers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const nonce = headers().get('x-nonce')

  console.log('nonce', nonce)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-2xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8 py-20'>
          {children}
        </div>
      </body>
    </html>
  )
}
